### PR TITLE
Added new interest for Sally

### PR DESCRIPTION
**Pull request by jisie**
Added `Ballet` to the list of interests. It should be displaying as the last interest.

Instructions to test:
```
git fetch --all
git checkout jd-add-new-interest
serve
```
Please make sure you can see `Ballet` listed.

### CODE REVIEW

**Comment by Scott47** [comment]
👍  The new interest is displayed when I serve your branch on my local machine.

**Comment by sageklein** [comment]
:+1:

**Review by Scott47 — APPROVED** [review]
Tested branch js-add-new-interest, new interest renders when I run server 👍

**Review by BryanNilsen — APPROVED** [review]
Fetched branch.
Tested in browser.
New Interest displayed as indicated.
👍

**Review by sageklein — APPROVED** [review]

**Pull request merged**
